language: c
sudo: enabled
dist: trusty
compiler: gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install -y cmake libglib2.0-dev libraptor2-dev
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: cmake --build .
